// Random/Web/React/todolist/src/components/layout/Header.js
import React from 'react';
import { Link } from 'react-router-dom';

function Header() {
    return (
        <header style={headerStyle}>
            <h1>TodoList</h1>
            <Link style={linkStyle} to="/">Home</Link> | <Link style={linkStyle} to="/about">About</Link>
        </header>
    )
}

const headerStyle = {
    background: '#333',
    color: '#fff',
    textAlign: 'center',
    padding: '10px'
}

const linkStyle = {
    color: '#fff'
}

export default Header

// Random/VueJS/crashcourse/src/components/layout/Header.vue
<template>
    <header class="header">
        <h1>TodoList</h1>
        <div id="nav">
            <router-link to="/">Home</router-link> |
            <router-link to="/about">About</router-link>
        </div>
    </header>
</template>

<script>
  export default {
    name: 'Header'
  }
</script>

<style scoped>
    .header {
        background: #333;
        color: white;
        text-align: center;
        padding: 10px;
    }

    .header a {
        color: white;
        padding: 5px;
        text-decoration: none;
    }
</style>
