// Random/VueJS/crashcourse/src/components/AddTodo.vue
<template>
    <div>
        <form @submit="addTodo">
            <input type="text" v-model="title" name="title" placeholder="Add Todo..."/>
            <input type="submit" class="btn"/>
        </form>
    </div>
</template>

<script>
  export default {
    name: 'AddTodo',
    data() {
      return {
        title: ''
      }
    },
    methods: {
      addTodo(e) {
        e.preventDefault();
        const newTodo = {
          title: this.title,
          completed: false
        };
        this.$emit('add-todo', newTodo);
        this.title = '';
      }
    }
  }
</script>

<style scoped>
    form {
        display: flex;
    }

    input[type="text"] {
        flex: 10;
        padding: 5px;
    }

    input[type="submit"] {
        flex: 2;
    }
</style>

// Random/Web/React/todolist/src/components/AddTodo.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

export class AddTodo extends Component {
	state = {
		title: ''
	}
	onSubmit = (e) => {
		e.preventDefault();
		if (this.state.title !== '') {
			this.props.addTodo(this.state.title);
		}
		this.setState({ title: '' });
	}
	onChange = (e) => {
		this.setState({ [e.target.name]: e.target.value });
	}
	render() {
		return (
			<form onSubmit={this.onSubmit} style={{ display: 'flex' }}>
				<input
					type="text"
					name="title"
					style={{ flex: '10', padding: '5px' }}
					placeholder="Add Todo ..."
					value={this.state.title}
					onChange={this.onChange}
				/>
				<input
					type="submit"
					value="Submit"
					className="btn"
					style={{ flex: '1' }}
				/>
			</form>
		)
	}
}

// PropTypes
AddTodo.propTypes = {
	addTodo: PropTypes.func.isRequired
}

export default AddTodo
